language: python
python:
  - "3.4"

branches:
  only:
    - master

sudo: false

install:
  - pip install -r requirements.txt
  - pip install happy==1.2.0 coverage coveralls pep8 behave selenium

script:
  - coverage run --source='.' manage.py test
  - export HEROKU_APP_NAME="travis-minicomi-$TRAVIS_BUILD_ID"
  - happy up $HEROKU_APP_NAME \
      --auth-token $HEROKU_AUTH_TOKEN \
      --env SUPERUSER_NAME=$SUPERUSER_NAME \
      --env SUPERUSER_PASSWORD=$SUPERUSER_PASSWORD \
      --tarball-url https://github.com/$TRAVIS_REPO_SLUG/tarball/$TRAVIS_COMMIT/
  - export MINICOMI_BASE_URL="https://$HEROKU_APP_NAME.herokuapp.com"
  - behave
  - happy down travis-minicomi-$TRAVIS_BUILD_ID \
      --auth-token $HEROKU_AUTH_TOKEN \
      --force

after_success: coveralls
