language: python
python:
  - "3.4"

branches:
  only:
    - master

sudo: false

install:
  - pip install -r requirements.txt
  - pip install happy==1.2.0 coverage coveralls pep8 behave selenium

script:
  - coverage run --source='.' manage.py test
  - happy up --auth-token $HEROKU_AUTH_TOKEN \
      --env SUPERUSER_NAME=$SUPERUSER_NAME \
      --env SUPERUSER_PASSWORD=$SUPERUSER_PASSWORD \
      --tarball-url https://github.com/$TRAVIS_REPO_SLUG/tarball/$TRAVIS_COMMIT/
  - export MINICOMI_BASE_URL="https://`cat .happy`.herokuapp.com"
  - behave
  - happy down --auth-token $HEROKU_AUTH_TOKEN

after_success: coveralls
