version: 2
jobs:
  test:
    docker:
      - image: nibbleproject/nibble-ci
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            pip install -r requirements.txt
            pip install -r requirements-test.txt
      - run:
          name: Run tests
          command: CI=true make test
      - run:
          name: Report Coverage
          command: 
            coveralls
  deploy_staging:
    steps:
      - checkout
      - run:
          name: Configure Heroku
          command: |
            cat > ~/.netrc << EOF
            machine api.heroku.com
              login $HEROKU_LOGIN
              password $HEROKU_API_KEY
            EOF
      - add_ssh_keys:
          fingerprints:
            - ""
      - run:
          name: Deploy to staging
          command: |
            heroku git:remote --app $HEROKU_APP_NAME
            git push heroku master
  deploy_production:
    steps:
      - checkout
      - run:
          name: Configure Heroku
          command: |
            cat > ~/.netrc << EOF
            machine api.heroku.com
              login $HEROKU_LOGIN
              password $HEROKU_API_KEY
            EOF
      - add_ssh_keys:
          fingerprints:
            - ""
      - run:
          name: Deploy to production
          command: |
            heroku git:remote --app $HEROKU_APP_NAME
            heroku pipelines:promote

workflows:
  version: 2
  master:
    jobs:
      - test
      - deploy_staging:
          requires:
            - test
          filters:
            branches:
              only: master
      - hold:
          type: approval
          requires:
            - deploy_staging
          filters:
            branches:
              only: master
      - deploy_production:
          requires:
            - hold
          filters:
            branches:
              only: master
